name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - run: go get -v -t -d ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: -E golint,gofmt,goimports

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - run: go get -v -t -d ./...

      - name: Build
        run: make build

      - name: Test
        run: make test
  tag-full:
    name: tag full
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kobtea/release-tag-action@a07ecb3e90cac36ce49801a9f49a6529098d3c48
        with:
          message: gogo __VERSION__
  tag-major:
    name: tag major
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kobtea/release-tag-action@a07ecb3e90cac36ce49801a9f49a6529098d3c48
        with:
          force: true
          only_major_version: true
